#!/usr/bin/env python3 

import json
import requests as req


baseurl = 'https://bitmovin-a.akamaihd.net/content/multi-codec'
codecs = ['h264','hevc','vp9']
representations = {'h264':[350,650,1000,1500,3000,5000,8000], 
        'hevc':[175,325,500,750,1500,2500,4000],
        'vp9':[245,455,700,1050,2100,3500,5600] }

resolutions = [[320,'180p'],[480,'270p'],[640,'360p'],[854,'480p'],[1280,'720p'],[1920,'1080p_1'],[1920,'1080p_2']]

manifest = 'stream.mpd'

# r = requests.get(url)
# r.status_code = 200
# l = len(r.content)

#for every codec and representation we fetch the size of the segment
seginfo = {}

for codec in representations:
    seginfo[codec] = {}
    for i,br in enumerate(representations[codec]):
        sidx = 0
        segsizes = []
        while True:
            ext = 'chk' if codec=='vp9' else 'm4s'
            base = "{}/{}/video/{}/segment_{}.{}".format(baseurl, codec, resolutions[i][1], sidx, ext)
            print(base)
            r = req.get(base)
            print("{}:{}".format(r.status_code, len(r.content)))
            if r.status_code!=200:
                break
            segsizes.append(len(r.content))
            sidx +=1

        seginfo[codec][br] = segsizes

#write out in json format all the segment information for these representations
# format is [codec][representation_bitrate][segment_sizes] -> [string][int][list]
with open('seginfo.json', 'w') as file:
    file.write(json.dumps(seginfo, indent=4))




